"""
This type stub file was generated by pyright.
"""

def setup_openapi_client(api_client_klass, api_klass, config, openapi_config, pool_threads, api_version=..., **kwargs):
    ...

def build_plugin_setup_client(config, openapi_config, pool_threads): # -> Callable[..., Any]:
    ...

