"""This type stub file was generated by pyright."""

from pinecone.core.openapi.data.models import SparseValues

class SparseValuesFactory:
    @staticmethod
    def build(input: dict | SparseValues) -> SparseValues: ...
