"""This type stub file was generated by pyright.
"""

from pinecone.core.openapi.data.models import Vector

class VectorFactory:
    @staticmethod
    def build(item: Vector | tuple | dict, check_type: bool = ...) -> Vector: ...
