"""
This type stub file was generated by pyright.
"""

from typing import Dict, Tuple, Union
from pinecone.core.openapi.data.models import Vector

class VectorFactory:
    @staticmethod
    def build(item: Union[Vector, Tuple, Dict], check_type: bool = ...) -> Vector:
        ...
    


