# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

# This is docker-compose for local testing, DO NOT USE IN PRODUCTION
services:
  ai4edu-api-server:
    image: ai4edu-api-server:local
    container_name: ai4edu-api-server-local
    build:
      context: .
    volumes:
      - ./ai4edu_api_volume_local:/app/volume_cache:rw
    ports:
      - 8000:5000
    secrets:
      - ai4edu-secret
    networks:
      - localnet
  redis-local-server:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - 8001:8001
    networks:
      - localnet

networks:
  localnet:

secrets:
  ai4edu-secret:
    file: .env

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

