"""
This type stub file was generated by pyright.
"""

from pinecone.core.openapi.control.models import IndexModel as OpenAPIIndexModel

class IndexModel:
    def __init__(self, index: OpenAPIIndexModel) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __getattr__(self, attr): # -> Any:
        ...
    
    def __getitem__(self, key): # -> Any:
        ...
    


