"""This type stub file was generated by pyright."""

from typing import NamedTuple

class Pagination(NamedTuple):
    next: str

class ListResponse(NamedTuple):
    namespace: str
    vectors: list
    pagination: Pagination | None
