# This is the docker-compose file for in cloud development and production
version: "1.1.1"
services:
  ai4edu-admin-dev-server:
    container_name: ai4edu-admin-dev-server
    secrets:
      - ai4edu-secret
    image: ghcr.io/os-computational-economics/ai4edu-admin:dev
    volumes:
      - ./admin_dev_volume:/app/volume_cache:rw
    networks:
      - devnet
    depends_on:
      - nginx-server
  ai4edu-admin-prod-server:
    container_name: ai4edu-admin-prod-server
    secrets:
      - ai4edu-secret
    image: ghcr.io/os-computational-economics/ai4edu-admin:prod
    volumes:
      - ./admin_prod_volume:/app/volume_cache:rw
    networks:
      - prodnet
    depends_on:
      - nginx-server
  ai4edu-user-dev-server:
    container_name: ai4edu-user-dev-server
    secrets:
      - ai4edu-secret
    image: ghcr.io/os-computational-economics/ai4edu-user:dev
    volumes:
      - ./user_dev_volume:/app/volume_cache:rw
    networks:
      - devnet
    depends_on:
      - nginx-server
  ai4edu-user-prod-server:
    container_name: ai4edu-user-prod-server
    secrets:
      - ai4edu-secret
    image: ghcr.io/os-computational-economics/ai4edu-user:prod
    volumes:
      - ./user_prod_volume:/app/volume_cache:rw
    networks:
      - prodnet
    depends_on:
      - nginx-server
  redis-dev-server:
    container_name: redis-dev-server
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis_dev_volume:/data:rw
    networks:
      - devnet
  redis-prod-server:
    container_name: redis-prod-server
    image: redis/redis-stack-server:latest
    volumes:
      - ./redis_prod_volume:/data:rw
    networks:
      - prodnet
  nginx-server:
    container_name: nginx-server
    image: nginx:latest
    environment:
      - DOMAIN=ai4edu-api.jerryang.org
      - ADMIN_DEV_NAME=ai4edu-admin-dev-server
      - USER_DEV_NAME=ai4edu-user-dev-server
      - ADMIN_PROD_NAME=ai4edu-admin-prod-server
      - USER_PROD_NAME=ai4edu-user-prod-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./files/nginx_conf/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./files/ssl:/etc/nginx/ssl:ro
    networks:
      - devnet
      - prodnet
networks:
  # Explicitly mark networks as bridges, as DNS resolution only works on bridged networking
  devnet:
    driver: bridge
  prodnet:
    driver: bridge
secrets:
  ai4edu-secret:
    file: edcwsxqaz
