name: Format code with formatter
on:
  workflow_dispatch:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run the formatter
        run: |-
          nix fmt;\
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format repo
